#Compilation command assuming GCC and NVIDIA OpenCL SDK located in the default locations
convolution:
#	gcc -g bmpfuncs.c convolution.c -I /usr/local/cuda-3.2/sdk/OpenCL/common/inc -lOpenCL -lm -o convolution     
	gcc -g bmpfuncs.c convolution.c -I /usr/local/cuda-4.0/include -lOpenCL -lm -o convolution     

clean:
	rm convolution
