#Compilation command assuming GCC and NVIDIA OpenCL SDK located in the default locations
convolution:
	gcc -g 2Dconvolution.c -I /usr/local/cuda-4.0/include -lOpenCL -lm -o 2Dconvolution     
clean:
	rm -f 2Dconvolution
