#Compilation command assuming GCC and NVIDIA OpenCL SDK located in the default locations
rotation:
#	gcc bmpfuncs.c rotation.c -I /usr/local/cuda-3.2/sdk/OpenCL/common/inc -lOpenCL -lm -o rotation
	gcc bmpfuncs.c rotation.c -I /usr/local/cuda-4.0/include -lOpenCL -lm -o rotation

clean:
	rm rotation 
